# Generated by Django 5.2.1 on 2025-05-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Укажите TG ник",
                max_length=50,
                null=True,
                verbose_name="TG",
            ),
        ),
    ]
