# Generated by Django 5.2.1 on 2025-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Укажите Имя пользователя",
                max_length=50,
                null=True,
                verbose_name="Имя",
            ),
        ),
    ]
