# Generated by Django 5.2.1 on 2025-05-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Привычка"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Выберете время когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время старта",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите действие привычки",
                        max_length=300,
                        null=True,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        help_text="Укажите периодичность выполнения привычки",
                        verbose_name="Периодичность выполнения привычки в неделю",
                    ),
                ),
                (
                    "remuneration",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Вознаграждение после выполнения привычки",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать для общего доступа",
                        verbose_name="Публикация в общем доступе",
                    ),
                ),
            ],
        ),
    ]
